stages:
  - deploy

deploy-to-production:
  stage: deploy
  tags:
    - docker_try
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - echo 'ReDeploy with deploy file in EC2.'
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@$EC2_IP "$DEPLOY_COMMAND"
